# Generated by Django 4.2.11 on 2024-04-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_user_id', models.IntegerField(verbose_name='发送者ID')),
                ('content', models.TextField(verbose_name='聊天内容')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('is_ai_sent', models.BooleanField(default=False, verbose_name='由AI发送')),
            ],
            options={
                'verbose_name': '聊天历史',
                'verbose_name_plural': '聊天历史',
            },
        ),
    ]
