# Generated by Django 4.2.11 on 2024-04-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_uploadform_alter_chathistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadform',
            name='img_name',
            field=models.CharField(default='png', max_length=155, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='uploadform',
            name='status',
            field=models.CharField(max_length=100, verbose_name='状态'),
        ),
    ]
